-- Migration: create RPC get_components_for_recipes
-- Generated by Cascade on 2025-08-04
-- Purpose: Replace legacy get_components_for_preparations with recipe-centric version.

-- 1. Safety: drop old helper (keep if other code still calls it)
DROP FUNCTION IF EXISTS public.get_components_for_preparations(_prep_ids uuid[]);

-- 2. Create new function
CREATE OR REPLACE FUNCTION public.get_components_for_recipes(
  _recipe_ids uuid[]
)
RETURNS TABLE (
  recipe_id uuid,
  component_id uuid,
  amount numeric,
  unit public.unit, 
  is_preparation boolean
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT
    rc.recipe_id,
    rc.component_id,
    rc.amount,
    rc.unit AS unit,
    (c.component_type = 'Preparation') AS is_preparation
  FROM recipe_components rc
  JOIN components c ON c.component_id = rc.component_id
  WHERE rc.recipe_id = ANY(_recipe_ids);
$$;

-- 3. Grant execution permissions (adjust roles as needed)
GRANT EXECUTE ON FUNCTION public.get_components_for_recipes(uuid[]) TO anon;
GRANT EXECUTE ON FUNCTION public.get_components_for_recipes(uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_components_for_recipes(uuid[]) TO service_role;
