-- Schema Cleanup Migration
-- 2025-07-23 22:00 (auto-generated by Cascade)
--
-- Fixes and clean-ups requested:
--   * Update fp_namespace() constant to use "roa-preparation-fingerprint" DNS namespace
--   * Drop unnecessary notes column from recipe_components
--   * Drop disused languages table
--   * Set a fixed search_path for all functions in the public schema to satisfy
--     Supabase security lint (function_search_path_mutable)

BEGIN;

-- -------------------------------------------------------------------
-- 1. Fingerprint namespace constant
-- -------------------------------------------------------------------
DROP FUNCTION IF EXISTS public.fp_namespace();
CREATE OR REPLACE FUNCTION public.fp_namespace()
RETURNS uuid
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
    SELECT public.uuid_generate_v5(public.uuid_ns_dns(), 'roa-preparation-fingerprint');
$$;

-- -------------------------------------------------------------------
-- 2. Drop unused column from recipe_components
-- -------------------------------------------------------------------
ALTER TABLE IF EXISTS public.recipe_components
    DROP COLUMN IF EXISTS notes;

-- -------------------------------------------------------------------
-- 3. Remove disused languages table
-- -------------------------------------------------------------------
DROP TABLE IF EXISTS public.languages CASCADE;

-- -------------------------------------------------------------------
-- 4. Move pg_trgm extension to extensions schema for security compliance
-- -------------------------------------------------------------------
-- Ensure target schema exists
CREATE SCHEMA IF NOT EXISTS extensions;
-- Move extension only if currently in public
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_extension e
        JOIN pg_namespace n ON n.oid = e.extnamespace
        WHERE e.extname = 'pg_trgm'
          AND n.nspname = 'public'
    ) THEN
        -- Moving preserves dependent objects like indexes
        ALTER EXTENSION pg_trgm SET SCHEMA extensions;
    END IF;
END;
$$;

-- -------------------------------------------------------------------
-- 5. Ensure deterministic search_path on all public functions
-- -------------------------------------------------------------------
DO $$
DECLARE
    r record;
BEGIN
    FOR r IN
        SELECT p.proname,
               oidvectortypes(p.proargtypes) AS argtypes
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = 'public'
          AND p.prokind = 'f'          -- functions only (exclude aggregates, etc.)
          AND pg_get_userbyid(p.proowner) = current_user -- only functions owned by current role
    LOOP
        EXECUTE format(
            'ALTER FUNCTION public.%I(%s) SET search_path = '''';',
            r.proname,
            r.argtypes
        );
    END LOOP;
END;
$$;

COMMIT;
